import test from 'node:test';
import assert from 'node:assert/strict';
import { EXPERIMENTS } from '../src/em-course-coaxial.js';
import { EPS0 } from '../src/em-course-constants.js';

const charge = EXPERIMENTS.find(experiment => experiment.id === 'coax-charge');
const voltage = EXPERIMENTS.find(experiment => experiment.id === 'coax-voltage');
const geometry = Object.freeze({ a: .001, b: .004, c: .005, epsilonR: 2.5 });
const chargeParams = Object.freeze({ ...geometry, lambda: 1e-9 });
const voltageParams = Object.freeze({ ...geometry, voltage: 100 });
// Immutable rounded expectations from parent c6a9e2d, never generated by production code.
const FIXTURE = Object.freeze({ Er: 3595.02071447, potential: 4.98375694458,
  deltaV: 9.96751388915, capacitance: 1.00325919895e-10,
  voltageLambda: 1.00325919895e-8, voltageEr: 36067.3760222 });
const value = (result, key) => result.scalars.find(item => item.key === key)?.value;
function near(actual, expected, absolute = 1e-11, relative = 1e-10) {
  assert.ok(Number.isFinite(actual), `nonfinite actual ${actual}`);
  assert.ok(Math.abs(actual - expected) <= absolute + relative * Math.abs(expected), `${actual} != ${expected}`);
}
function finiteNumbers(result) {
  for (const vector of Object.values(result.vectors)) for (const number of vector) assert.ok(Number.isFinite(number));
  for (const item of result.scalars) assert.ok(Number.isFinite(item.value));
}

test('course constants and two separate controlled-quantity definitions match contract', () => {
  assert.equal(EPS0, 8.8541878188e-12);
  assert.deepEqual(EXPERIMENTS.map(item => item.id), ['coax-charge', 'coax-voltage']);
  assert.ok(charge.parameters.some(item => item.key === 'lambda'));
  assert.ok(!charge.parameters.some(item => item.key === 'voltage'));
  assert.ok(voltage.parameters.some(item => item.key === 'voltage'));
  for (const experiment of EXPERIMENTS) {
    assert.equal(experiment.modelKind, 'analytic-symmetry');
    assert.equal(experiment.view.kind, 'coax-cross-section');
    for (const key of ['assumptions', 'validity', 'singularities', 'formulas', 'references']) assert.ok(experiment[key].length > 0);
    assert.ok(experiment.references[0].url.endsWith('/8-1-capacitors-and-capacitance'));
    assert.equal(experiment.evaluate(Object.fromEntries(experiment.parameters.map(item => [item.key, item.initial])), experiment.probeDefault).status, 'valid');
  }
});

test('fixed charge independent SI fixture: E/D/V/deltaV/Cprime', () => {
  const result = charge.evaluate(chargeParams, [.002, 0, 0]);
  assert.equal(result.status, 'valid');
  assert.equal(result.region, 'dielectric');
  near(result.vectors.E[0], FIXTURE.Er, 1e-7);
  near(result.vectors.D[0], 7.957747154594768e-8, 1e-18);
  near(value(result, 'potential'), FIXTURE.potential);
  near(value(result, 'deltaV'), FIXTURE.deltaV);
  near(value(result, 'capacitancePerLength'), FIXTURE.capacitance, 1e-18);
  assert.equal(value(result, 'lambda'), 1e-9);
  assert.equal(result.vectors.E[1], 0);
  assert.equal(result.vectors.E[2], 0);
  finiteNumbers(result);
});

test('fixed voltage independent SI fixture: induced lambda, E and V', () => {
  const result = voltage.evaluate(voltageParams, [.002, 0, 0]);
  near(value(result, 'lambda'), FIXTURE.voltageLambda, 1e-18);
  near(result.vectors.E[0], FIXTURE.voltageEr, 1e-7);
  near(value(result, 'potential'), 50);
  near(value(result, 'deltaV'), 100);
  near(value(result, 'capacitancePerLength'), FIXTURE.capacitance, 1e-18);
});

test('fixed voltage epsilon increase leaves E/V invariant and increases D/lambda/Cprime', () => {
  const first = voltage.evaluate(voltageParams, [.0012, .0016, 3]);
  const second = voltage.evaluate({ ...voltageParams, epsilonR: 10 }, [.0012, .0016, 3]);
  assert.deepEqual(second.vectors.E, first.vectors.E);
  assert.equal(value(second, 'potential'), value(first, 'potential'));
  for (let axis = 0; axis < 3; axis++) near(second.vectors.D[axis], 4 * first.vectors.D[axis], 1e-18);
  for (const key of ['lambda', 'capacitancePerLength']) near(value(second, key), 4 * value(first, key), 1e-18);
});

test('fixed charge epsilon increase reduces E/V while preserving D/lambda', () => {
  const first = charge.evaluate(chargeParams, [.002, 0, 0]);
  const second = charge.evaluate({ ...chargeParams, epsilonR: 10 }, [.002, 0, 0]);
  near(second.vectors.E[0], first.vectors.E[0] / 4, 1e-7);
  near(value(second, 'potential'), value(first, 'potential') / 4);
  near(value(second, 'deltaV'), value(first, 'deltaV') / 4);
  assert.deepEqual(second.vectors.D, first.vectors.D);
  assert.equal(value(second, 'lambda'), value(first, 'lambda'));
});

test('signed excitation gives radial direction, negative V, z invariance and zero excitation', () => {
  for (const [experiment, params, control] of [[charge, chargeParams, 'lambda'], [voltage, voltageParams, 'voltage']]) {
    const positive = experiment.evaluate(params, [0, -.002, 0]);
    const negative = experiment.evaluate({ ...params, [control]: -params[control] }, [0, -.002, 42]);
    assert.ok(positive.vectors.E[1] < 0);
    assert.ok(negative.vectors.E[1] > 0);
    near(negative.vectors.E[1], -positive.vectors.E[1], 1e-7);
    near(value(negative, 'potential'), -value(positive, 'potential'));
    const zero = experiment.evaluate({ ...params, [control]: 0 }, [.002, 0, 0]);
    assert.equal(zero.status, 'valid');
    near(Math.hypot(...zero.vectors.E), 0);
    assert.equal(value(zero, 'potential'), 0);
    assert.ok(value(zero, 'capacitancePerLength') > 0);
  }
});

test('inner conductor including origin: zero E/D with constant deltaV', () => {
  for (const point of [[0, 0, 0], [.0005, 0, 9]]) {
    const result = charge.evaluate(chargeParams, point);
    assert.equal(result.status, 'valid');
    assert.equal(result.region, 'inner-conductor');
    assert.deepEqual(result.vectors, { E: [0, 0, 0], D: [0, 0, 0] });
    near(value(result, 'potential'), FIXTURE.deltaV);
  }
});

test('outer conductor and exterior have E=D=V=0 under displayed balance assumptions', () => {
  for (const [r, region] of [[.0045, 'outer-conductor'], [.006, 'exterior']]) {
    const result = charge.evaluate(chargeParams, [r, 0, 0]);
    assert.equal(result.region, region);
    assert.equal(result.status, 'valid');
    assert.deepEqual(result.vectors, { E: [0, 0, 0], D: [0, 0, 0] });
    assert.equal(value(result, 'potential'), 0);
  }
  const changedThickness = charge.evaluate({ ...chargeParams, c: .1 }, [.002, 0, 0]);
  const original = charge.evaluate(chargeParams, [.002, 0, 0]);
  assert.deepEqual(changedThickness.vectors, original.vectors);
  assert.equal(value(changedThickness, 'capacitancePerLength'), value(original, 'capacitancePerLength'));
});

test('a/b/c surfaces expose signed two-sided limits without a fabricated single vector', () => {
  for (const [r, surface, potential, erMinus, erPlus] of [
    [.001, 'a', FIXTURE.deltaV, 0, 7190.04142894],
    [.004, 'b', 0, 1797.510357235, 0],
    [.005, 'c', 0, 0, 0],
  ]) {
    const result = charge.evaluate(chargeParams, [r, 0, 0]);
    assert.equal(result.status, 'boundary');
    assert.equal(result.region, `surface-${surface}`);
    assert.deepEqual(result.vectors, {});
    assert.ok(result.reason);
    near(value(result, 'potential'), potential);
    near(value(result, 'ErInside'), erMinus, 1e-7);
    near(value(result, 'ErOutside'), erPlus, 1e-7);
    finiteNumbers(result);
    if (r !== .005) {
      const negative = charge.evaluate({ ...chargeParams, lambda: -1e-9 }, [r, 0, 0]);
      near(value(negative, 'DrOutside') - value(negative, 'DrInside'),
        -(value(result, 'DrOutside') - value(result, 'DrInside')), 1e-18);
    }
  }
});

test('actual neighboring points match conductor/gap limits with no tolerance clamp', () => {
  assert.equal(charge.evaluate(chargeParams, [.001 - 1e-12, 0, 0]).region, 'inner-conductor');
  assert.equal(charge.evaluate(chargeParams, [.001 + 1e-12, 0, 0]).region, 'dielectric');
  assert.equal(charge.evaluate(chargeParams, [.004 - 1e-12, 0, 0]).region, 'dielectric');
  assert.equal(charge.evaluate(chargeParams, [.004 + 1e-12, 0, 0]).region, 'outer-conductor');
});

test('reject bad radius order, epsilon, nonfinite/missing/non-numeric parameters', () => {
  const bad = [null, [], {}, { ...chargeParams, a: 0 }, { ...chargeParams, a: -.001 },
    { ...chargeParams, a: .004 }, { ...chargeParams, b: .0005 }, { ...chargeParams, c: .004 },
    { ...chargeParams, epsilonR: 0 }, { ...chargeParams, epsilonR: -2 },
    { ...chargeParams, lambda: NaN }, { ...chargeParams, lambda: Infinity },
    { ...chargeParams, lambda: '1e-9' }, { ...chargeParams, a: undefined }, { ...chargeParams, extra: -Infinity }];
  for (const params of bad) {
    const result = charge.evaluate(params, [.002, 0, 0]);
    assert.equal(result.status, 'invalid');
    assert.ok(result.reason);
    assert.deepEqual(result.vectors, {});
    assert.deepEqual(result.scalars, []);
  }
  assert.equal(voltage.evaluate({ ...voltageParams, voltage: Infinity }, [.002, 0, 0]).status, 'invalid');
});

test('reject malformed/nonfinite probes and unrepresentable derived results', () => {
  for (const point of [null, [], [0, 0], [0, 0, 0, 0], [NaN, 0, 0], [0, Infinity, 0], ['0', 0, 0]]) {
    assert.equal(charge.evaluate(chargeParams, point).status, 'invalid');
  }
  for (const [params, point] of [[{ ...chargeParams, lambda: 1e308 }, [.002, 0, 0]],
    [{ ...chargeParams, epsilonR: Number.MIN_VALUE }, [.002, 0, 0]],
    [chargeParams, [Number.MAX_VALUE, Number.MAX_VALUE, 0]]]) {
    const result = charge.evaluate(params, point);
    assert.equal(result.status, 'invalid');
    assert.deepEqual(result.vectors, {});
    finiteNumbers(result);
  }
});

test('bounded independent radial quadrature passes both fixtures and negative/zero drive', () => {
  for (const [experiment, params, control] of [[charge, chargeParams, 'lambda'], [voltage, voltageParams, 'voltage']]) {
    for (const multiplier of [1, -1, 0]) {
      const rows = experiment.verify({ ...params, [control]: multiplier * params[control] });
      assert.equal(rows.length, 1);
      assert.equal(rows[0].status, 'pass');
      assert.ok(rows[0].method.includes('quadrature'));
      assert.ok(Number.isFinite(rows[0].actual));
      assert.ok(Number.isFinite(rows[0].expected));
    }
  }
});

test('invalid or numerically inseparable gap verification is explicitly skipped', () => {
  for (const params of [{ ...chargeParams, b: .0001 }, { ...chargeParams, lambda: Infinity },
    { ...chargeParams, b: .0010000000000000002 }]) {
    const rows = charge.verify(params);
    assert.equal(rows[0].status, 'skipped');
    assert.ok(rows[0].reason);
    assert.equal(rows[0].actual, undefined);
  }
});

test('review regression b/a=20 converges without changing evaluation or tolerances', () => {
  for (const [experiment, control, drive] of [[voltage, 'voltage', 100], [charge, 'lambda', 1e-9]]) {
    for (const sign of [1, -1, 0]) {
      const params = { a: .001, b: .020, c: .021, epsilonR: 2.5, [control]: sign * drive };
      const before = experiment.evaluate(params, [.002, 0, 0]);
      const [row] = experiment.verify(params);
      assert.equal(row.status, 'pass', row.reason);
      assert.equal(row.absTolerance, 1e-10);
      assert.equal(row.relTolerance, 2e-6);
      assert.ok(row.method.includes('convergence'));
      assert.ok(row.sampleCount <= 1025);
      assert.ok(row.estimatedError <= row.absTolerance + row.relTolerance * Math.abs(row.expected));
      assert.deepEqual(experiment.evaluate(params, [.002, 0, 0]), before);
    }
  }
});

test('unresolved wide-gap verification reports numerical nonconvergence instead of physical fail', () => {
  const params = { a: 1e-6, b: 1, c: 1.1, epsilonR: 2.5, voltage: 100 };
  const evaluated = voltage.evaluate(params, [.002, 0, 0]);
  assert.equal(evaluated.status, 'valid');
  const [row] = voltage.verify(params);
  assert.equal(row.status, 'skipped');
  assert.ok(row.reason.includes('수렴'));
  assert.ok(row.sampleCount <= 1025);
  assert.ok(Number.isFinite(row.actual));
  assert.ok(Number.isFinite(row.estimatedError));
  assert.equal(row.expected, 100);
});
