// Focused native-browser scenario. Reuse the committed isolated HTTP/CDP driver;
// substitute only its scenario, not product code or existing assertions.
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const repo=fileURLToPath(new URL('../../../../',import.meta.url));
const driver=await readFile(new URL('../../../../results/COMBINED-STUDENT-FLOW-2026-10-05/native-check.mjs',import.meta.url),'utf8');
process.argv[2] ||= repo+'results/PROBLEM-MODE-SHORTCUT-2026-10-05/attempt-1';
process.argv[5]=fileURLToPath(new URL('../',import.meta.url));
const scenario=String.raw`
 const field=k=>'[data-circuit-course-key="'+k+'"]';
 const choose=async(k,value)=>{const selector=field(k);const index=await evaluate('Array.from(document.querySelector('+JSON.stringify(selector)+').options).findIndex(o=>o.value==='+JSON.stringify(value)+')');if(index<0)throw Error('Missing choice');await click(selector);await key('Home','Home',36);for(let i=0;i<index;i++)await key('ArrowDown','ArrowDown',40);await key('Enter','Enter',13);};
 const write=async(k,value)=>{await click(field(k));await key('a','KeyA',65,2);if(value)await send('Input.insertText',{text:value});else await key('Backspace','Backspace',8);};
 const ensureWs=async name=>{const getter={em:'getEMState',signals:'getSignalsCourseState','circuit-course':'getCircuitCourseState'}[name];try{await evaluate('window.__CIRCUIT_LAB__.ensureWorkspace('+JSON.stringify(name)+').then(()=>true)');}catch{}for(let n=0;n<80&&(await evaluate('window.__CIRCUIT_LAB__.'+getter+'()'))===null;n++)await new Promise(r=>setTimeout(r,100));};const ensureEMCourse=async()=>{for(let n=0;n<80&&(await evaluate('window.__CIRCUIT_LAB__.getEMState()?.course??null'))===null;n++)await new Promise(r=>setTimeout(r,100));};
 const state=()=>evaluate('window.__CIRCUIT_LAB__.getCircuitCourseState()');
 await navigate('/');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
 await click('#circuit-course-open');await ensureWs('circuit-course');await click('[data-circuit-course-experiment="problem"]');
 await write('symbolVoltage','V_test');await write('symbolR','R_load');await write('problemText','shortcut memo 390');
 await click('[data-circuit-course-apply]');
 check('symbolic answer applied',(await state()).status,'valid');
 await click('[data-circuit-course-mode="numeric"]');
 check('numeric shortcut focuses first missing voltage',await evaluate('document.activeElement.dataset.circuitCourseKey'),'voltage');
 check('numeric shortcut is draft and hides previous answer',await evaluate('window.__CIRCUIT_LAB__.getCircuitCourseState().status==="draft"&&document.querySelector("[data-circuit-course-results]").hidden'));
 for(const [k,v] of Object.entries({voltage:'100 V',frequencyHz:'50 Hz',sourceAngle:'0',r:'3 ohm',l:'12 mH',c:'100 uF'})) {
   if(await evaluate('!document.querySelector('+JSON.stringify(field(k))+').closest("label").hidden'))await write(k,v);
 }
 await click('[data-circuit-course-apply]');check('numeric answer applied',(await state()).status,'valid');
 const numericDrafts=(await state()).drafts;
 await click('[data-circuit-course-mode="symbolic"]');
 let s=await state();check('symbolic roundtrip applies preserved conditions',s.status==='valid'&&s.params.solutionMode==='symbolic'&&s.params.symbolVoltage==='V_test'&&s.params.symbolR==='R_load'&&s.params.problemText==='shortcut memo 390');
 for(const k of ['voltage','frequencyHz','sourceAngle','r','l','c'])check('preserved numeric draft '+k,s.drafts[k],numericDrafts[k]);
 await click('[data-circuit-course-derivation]>summary');
 await evaluate('Object.defineProperty(navigator,"clipboard",{configurable:true,value:{writeText:async text=>{window.__copy=text}}});true');
 await click('[data-circuit-course-derivation] [data-symbolic-copy]');
 check('symbolic copy contains current symbols and memo',await evaluate('window.__copy.includes("V_test")&&window.__copy.includes("R_load")&&window.__copy.includes("shortcut memo 390")'));
 await shot('symbolic-roundtrip-390');
 await click('[data-circuit-course-mode="numeric"]');check('numeric drafts survive second shortcut',(await state()).drafts.voltage,'100 V');
 await choose('problemKind','three');await write('frequencyHz','');await write('sourceAngle','');await write('x','6');
 await choose('solutionMode','symbolic');await click('[data-circuit-course-apply]');await click('[data-circuit-course-mode="numeric"]');
 check('three-phase skips empty optional frequency and focuses missing phase',await evaluate('document.activeElement.dataset.circuitCourseKey'),'sourceAngle');
 await write('sourceAngle','30');await click('[data-circuit-course-apply]');
 s=await state();check('three-phase computes with optional frequency blank',s.status==='valid'&&s.params.frequencyHz===null&&s.params.problemKind==='three');
 await click('[data-circuit-course-mode="symbolic"]');s=await state();
 check('three-phase structural conditions and draft survive symbolic return',s.status==='valid'&&s.params.problemKind==='three'&&s.drafts.frequencyHz===''&&s.drafts.sourceAngle==='30'&&s.drafts.symbolVoltage==='V_test');
 check('390px page fits viewport',await evaluate('document.documentElement.scrollWidth<=innerWidth'));
 await shot('three-phase-roundtrip-390');
 report.snapshots.final=s;
 report.status='PASS';
`;
const start=driver.indexOf(' const choose=');
const end=driver.indexOf('} catch(error)',start);
if(start<0||end<0)throw Error('Committed driver boundaries changed');
await import('data:text/javascript;base64,'+Buffer.from(driver.slice(0,start)+scenario+driver.slice(end)).toString('base64'));
